# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "_site"

[dev]
  command = "npm run dev" # Command to start your dev server
  functions = "netlify/functions"
  publish = "_site" # Folder with the static content for _redirect file
  targetPort = 8080

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
  to = "/.netlify/functions/get-card"
  from = "/api/get-card"
  status = 200

[[redirects]]
  to = "/.netlify/functions/ashbourne"
  from = "/api/ashbourne"
  status = 200

[[redirects]]
  to = "/.netlify/functions/zettle"
  from = "/api/zettle"
  status = 200

[[redirects]]
  to = "/.netlify/functions/stripe"
  from = "/api/stripe"
  status = 200

[[redirects]]
  to = "/.netlify/functions/sumup"
  from = "/api/sumup"
  status = 200

[[redirects]]
  to = "/.netlify/functions/zettle-webhooks"
  from = "/webhooks/zettle"
  status = 200

[[redirects]]
  to = "/.netlify/functions/getaddress"
  from = "/api/getaddress"
  status = 200

[[redirects]]
  to = "/.netlify/functions/stripe-customers"
  from = "/api/stripe-customers"
  status = 200
  
[[redirects]]
  to = "/.netlify/functions/timesheet"
  from = "/api/timesheet"
  status = 200

[[redirects]]
  to = "/.netlify/functions/age"
  from = "/api/age"
  status = 200

[[redirects]]
  to = "/.netlify/functions/new-social-members"
  from = "/api/new-social-members"
  status = 200

[[redirects]]
  to = "/.netlify/functions/webhooks"
  from = "/api/webhooks"
  status = 200

[[redirects]]
  to = "/.netlify/functions/invoice"
  from = "/api/invoice"
  status = 200

[[redirects]]
  to = "/.netlify/functions/success"
  from = "/api/success"
  status = 200
# [[edge_functions]]
# function = "cookies"
# path = "/*"

[[edge_functions]]
function = "card"
path = "/card"

[[edge_functions]]
function = "finder"
path = "/finder"

[[edge_functions]]
function = "ashbourne-json"
path = "/api/ashbourne-json"

[[edge_functions]]
function = "opening-times"
path = "/api/opening-times"

[[edge_functions]]
function = "stripe-join"
path = "/api/stripe-join"

[[edge_functions]]
function = "sumup-customers"
path = "/api/sumup-customers"

[[edge_functions]]
function = "customers"
path = "/api/customers"

[[edge_functions]]
function = "hello"
path = "/api/hello"





# # start-generated-edge-functions
[[edge_functions]]
function="resources"
path="/api/resources"

[[edge_functions]]
function="beer"
path="/api/beer"

[[edge_functions]]
function="sunday-lunch"
path="/api/sunday-lunch"

[[edge_functions]]
function="cocktails"
path="/api/cocktails"

[[edge_functions]]
function="wine"
path="/api/wine"

[[edge_functions]]
function="breakfast"
path="/api/breakfast"

[[edge_functions]]
function="spirits"
path="/api/spirits"

[[edge_functions]]
function="bar-food"
path="/api/bar-food"

[[edge_functions]]
function="soft-drinks"
path="/api/soft-drinks"

[[edge_functions]]
function="bbq"
path="/api/bbq"

[[edge_functions]]
function="tea-coffee"
path="/api/tea-coffee"

[[edge_functions]]
function="sports-teas"
path="/api/sports-teas"

[[edge_functions]]
function="euro-2024"
path="/api/euro-2024"

[[edge_functions]]
function="kids-menu"
path="/api/kids-menu"

[[edge_functions]]
function="liquer-coffee"
path="/api/liquer-coffee"

[[edge_functions]]
function="snacks"
path="/api/snacks"

[[edge_functions]]
function="halloween"
path="/api/halloween"

[[edge_functions]]
function="fizz-friday"
path="/api/fizz-friday"

[[edge_functions]]
function="mothers-day"
path="/api/mothers-day"

[[edge_functions]]
function="staff"
path="/api/staff"
# end-generated-edge-functions

